-- Aera Hilfe-Center: umfangreiche Startinhalte (idempotent, kundenfreundlich).

INSERT INTO "HelpCategory" ("id","title","slug","description","sortOrder","createdAt") VALUES ('hc_erste-schritte', 'Erste Schritte', 'erste-schritte', 'Aera kennenlernen, ein Konto erstellen und eine Community finden.', 10, now()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "HelpCategory" ("id","title","slug","description","sortOrder","createdAt") VALUES ('hc_community-starten', 'Deine Community starten', 'community-starten', 'In wenigen Minuten deine eigene Community unter deiner Marke aufbauen.', 11, now()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "HelpCategory" ("id","title","slug","description","sortOrder","createdAt") VALUES ('hc_mitgliedschaften-preise', 'Mitgliedschaften & Preise', 'mitgliedschaften-preise', 'Kostenlose und bezahlte Mitgliedschaften einrichten und verstehen.', 12, now()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "HelpCategory" ("id","title","slug","description","sortOrder","createdAt") VALUES ('hc_bezahlen-auszahlungen', 'Bezahlen & Auszahlungen', 'bezahlen-auszahlungen', 'Sichere Zahlung, Auszahlungen an Creator, Belege und Erstattungen.', 13, now()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "HelpCategory" ("id","title","slug","description","sortOrder","createdAt") VALUES ('hc_inhalte-erstellen', 'Inhalte: Beiträge, Kurse, Events & Newsletter', 'inhalte-erstellen', 'Veröffentlichen, unterrichten, Events halten und Mitglieder direkt erreichen.', 14, now()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "HelpCategory" ("id","title","slug","description","sortOrder","createdAt") VALUES ('hc_teilnehmen', 'Für Mitglieder: Teilnehmen', 'teilnehmen', 'Beitreten, mitmachen, lernen und in Kontakt bleiben.', 15, now()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "HelpCategory" ("id","title","slug","description","sortOrder","createdAt") VALUES ('hc_ki-funktionen', 'KI-Funktionen', 'ki-funktionen', 'Der KI-Assistent, Empfehlungen und das KI-Guthaben.', 16, now()) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "HelpCategory" ("id","title","slug","description","sortOrder","createdAt") VALUES ('hc_konto-marke-daten', 'Konto, Marke & Daten', 'konto-marke-daten', 'Profil und Sicherheit, Marke anpassen, Mitglieder verwalten und Daten herunterladen.', 17, now()) ON CONFLICT ("slug") DO NOTHING;

INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_erste-schritte_0', c."id", 'Was ist Aera?', 'Aera ist eine Plattform, auf der Creator ihre eigene Community unter ihrer eigenen Marke betreiben — mit Mitgliedschaften, Kursen, Events, Newsletter und mehr an einem Ort.

Als Mitglied trittst du der Community eines Creators bei und nimmst teil. Als Creator baust du deine eigene Community auf und entscheidest selbst über Inhalte, Preise und Aussehen.', 0, true, now() FROM "HelpCategory" c WHERE c."slug"='erste-schritte' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_erste-schritte_1', c."id", 'Wie erstelle ich ein Konto?', 'Klicke auf „Registrieren" und melde dich mit deiner E-Mail-Adresse und einem Passwort an.

Danach kannst du Communities beitreten — oder unter „Community starten" in wenigen Minuten deine eigene aufbauen.', 1, true, now() FROM "HelpCategory" c WHERE c."slug"='erste-schritte' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_erste-schritte_2', c."id", 'Brauche ich ein Konto, um mich umzusehen?', 'Viele Community-Seiten kannst du auch ohne Konto ansehen. Sobald du beitreten, mitschreiben oder etwas kaufen möchtest, brauchst du ein kostenloses Konto.', 2, true, now() FROM "HelpCategory" c WHERE c."slug"='erste-schritte' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_erste-schritte_3', c."id", 'Wie finde ich eine Community?', 'Über „Entdecken" auf der Startseite findest du öffentliche Communities. Oder du öffnest direkt die Adresse bzw. den Link, den dir ein Creator gegeben hat (zum Beispiel name.aera.so).', 3, true, now() FROM "HelpCategory" c WHERE c."slug"='erste-schritte' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_erste-schritte_4', c."id", 'Was kostet Aera?', 'Ein Konto anlegen und einer Community beitreten ist kostenlos.

Kosten entstehen nur, wenn du eine bezahlte Mitgliedschaft, einen Kurs, ein Produkt oder ein kostenpflichtiges Event eines Creators kaufst.

Für Creator ist das Starten einer Community kostenlos — beim Verkaufen behält Aera lediglich eine kleine Plattformgebühr.', 4, true, now() FROM "HelpCategory" c WHERE c."slug"='erste-schritte' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_community-starten_0', c."id", 'Wie starte ich meine eigene Community?', 'Wähle „Community starten". Du legst Namen und Adresse fest und triffst ein paar Grundeinstellungen. Danach landest du direkt in deinem Dashboard und kannst loslegen.', 0, true, now() FROM "HelpCategory" c WHERE c."slug"='community-starten' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_community-starten_1', c."id", 'Was ist das Dashboard?', 'Das Dashboard ist deine Schaltzentrale. Von hier aus richtest du Bereiche ein, veröffentlichst Inhalte, verwaltest Mitglieder, legst Mitgliedschaften und Preise fest, versendest Newsletter und siehst deine wichtigsten Zahlen.', 1, true, now() FROM "HelpCategory" c WHERE c."slug"='community-starten' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_community-starten_2', c."id", 'Was sind Bereiche?', 'Bereiche sind die Räume deiner Community — zum Beispiel ein Feed für Beiträge, Kurse, Events, ein Chat oder eine Mediathek.

Du entscheidest, welche Bereiche es gibt, wie sie heißen und wer sie sehen darf.', 2, true, now() FROM "HelpCategory" c WHERE c."slug"='community-starten' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_community-starten_3', c."id", 'Kann ich das Aussehen an meine Marke anpassen?', 'Ja. Du kannst Logo, Farben und Layout so einstellen, dass deine Community wie deine eigene Marke wirkt. Aera tritt bewusst in den Hintergrund — im Vordergrund stehst du.', 3, true, now() FROM "HelpCategory" c WHERE c."slug"='community-starten' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_community-starten_4', c."id", 'Bekomme ich eine eigene Adresse?', 'Ja. Deine Community erhält eine eigene Internetadresse (zum Beispiel deinname.aera.so). Eine eigene Wunsch-Domain lässt sich ebenfalls anbinden.', 4, true, now() FROM "HelpCategory" c WHERE c."slug"='community-starten' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_community-starten_5', c."id", 'Wie lade ich die ersten Mitglieder ein?', 'Teile einfach den Link zu deiner Community — über Social Media, Messenger oder E-Mail. Später erreichst du deine Mitglieder jederzeit direkt über den Newsletter, ganz ohne Algorithmus dazwischen.', 5, true, now() FROM "HelpCategory" c WHERE c."slug"='community-starten' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_mitgliedschaften-preise_0', c."id", 'Was ist eine Mitgliedschaft?', 'Eine Mitgliedschaft legt fest, was ein Mitglied in deiner Community sehen und tun darf. Es kann kostenlose und bezahlte Stufen geben — zum Beispiel „Frei", „Plus" und „Premium".', 0, true, now() FROM "HelpCategory" c WHERE c."slug"='mitgliedschaften-preise' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_mitgliedschaften-preise_1', c."id", 'Wie erstelle ich eine bezahlte Mitgliedschaft?', 'Im Dashboard legst du unter Mitgliedschaften eine neue Stufe an. Du wählst den Preis und die Abrechnung (monatlich oder jährlich) und bestimmst, welche Bereiche und Inhalte die Stufe freischaltet.', 1, true, now() FROM "HelpCategory" c WHERE c."slug"='mitgliedschaften-preise' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_mitgliedschaften-preise_2', c."id", 'Wie werde ich zahlendes Mitglied?', 'Wähle in der Community die gewünschte Mitgliedschaft und schließe die Zahlung über den sicheren Checkout ab. Dein Zugang schaltet sich sofort frei.', 2, true, now() FROM "HelpCategory" c WHERE c."slug"='mitgliedschaften-preise' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_mitgliedschaften-preise_3', c."id", 'Kann ich meine Mitgliedschaft ändern oder kündigen?', 'Ja. In deinen Mitgliedschafts-Einstellungen kannst du jederzeit wechseln oder kündigen.

Nach einer Kündigung bleibt dein Zugang bis zum Ende des bereits bezahlten Zeitraums bestehen.', 3, true, now() FROM "HelpCategory" c WHERE c."slug"='mitgliedschaften-preise' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_mitgliedschaften-preise_4', c."id", 'Was passiert nach dem Kauf mit meinem Zugang?', 'Bezahlte Bereiche und Inhalte schalten sich automatisch frei. Läuft eine Mitgliedschaft aus, werden sie wieder gesperrt — deine eigenen Beiträge und Daten bleiben dabei erhalten.', 4, true, now() FROM "HelpCategory" c WHERE c."slug"='mitgliedschaften-preise' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_bezahlen-auszahlungen_0', c."id", 'Wie bezahle ich sicher?', 'Zahlungen laufen über unseren Zahlungsdienstleister Stripe. Deine Zahlungsdaten werden dort verschlüsselt verarbeitet — Aera speichert selbst keine Kartendaten.', 0, true, now() FROM "HelpCategory" c WHERE c."slug"='bezahlen-auszahlungen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_bezahlen-auszahlungen_1', c."id", 'Welche Zahlungsmittel kann ich nutzen?', 'Je nach Land und Gerät stehen dir zum Beispiel Kredit- und Debitkarten sowie gängige digitale Zahlungsmittel zur Verfügung. Welche Optionen möglich sind, siehst du direkt an der Kasse.', 1, true, now() FROM "HelpCategory" c WHERE c."slug"='bezahlen-auszahlungen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_bezahlen-auszahlungen_2', c."id", 'Bekomme ich einen Beleg oder eine Rechnung?', 'Ja. Nach jedem Kauf erhältst du eine Bestätigung per E-Mail. Deine Käufe findest du außerdem jederzeit in deinen Kontoeinstellungen.', 2, true, now() FROM "HelpCategory" c WHERE c."slug"='bezahlen-auszahlungen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_bezahlen-auszahlungen_3', c."id", 'Wie bekomme ich als Creator meine Einnahmen?', 'Deine Auszahlungen laufen sicher über Stripe. Du hinterlegst einmalig deine Auszahlungsdaten, danach werden deine Einnahmen automatisch an dich überwiesen.', 3, true, now() FROM "HelpCategory" c WHERE c."slug"='bezahlen-auszahlungen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_bezahlen-auszahlungen_4', c."id", 'Welche Gebühren fallen für Creator an?', 'Aera behält beim Verkauf eine kleine Plattformgebühr. Zusätzlich können bei der Zahlungsabwicklung Gebühren des Zahlungsdienstleisters anfallen. Der Rest deiner Einnahmen gehört dir.', 4, true, now() FROM "HelpCategory" c WHERE c."slug"='bezahlen-auszahlungen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_bezahlen-auszahlungen_5', c."id", 'Wie funktionieren Erstattungen?', 'Eine Erstattung stößt der jeweilige Creator an. Bei Fragen zu einem Kauf wende dich zuerst an den Creator der Community — oder an unseren Support, wenn du nicht weiterkommst.', 5, true, now() FROM "HelpCategory" c WHERE c."slug"='bezahlen-auszahlungen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_inhalte-erstellen_0', c."id", 'Wie veröffentliche ich einen Beitrag?', 'Öffne den passenden Bereich, wähle „Neuer Beitrag", füge Text und Medien hinzu und veröffentliche. Du legst dabei fest, welche Mitglieder den Beitrag sehen dürfen.', 0, true, now() FROM "HelpCategory" c WHERE c."slug"='inhalte-erstellen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_inhalte-erstellen_1', c."id", 'Wie erstelle ich einen Kurs?', 'Lege einen Kurs-Bereich an und füge Lektionen oder Module hinzu. Du entscheidest, ob der Kurs frei zugänglich oder Teil einer bezahlten Mitgliedschaft ist.', 1, true, now() FROM "HelpCategory" c WHERE c."slug"='inhalte-erstellen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_inhalte-erstellen_2', c."id", 'Wie plane ich ein Event?', 'Im Events-Bereich legst du Titel, Zeitpunkt und Details fest. Mitglieder können zusagen. Events kannst du kostenlos oder kostenpflichtig anbieten.', 2, true, now() FROM "HelpCategory" c WHERE c."slug"='inhalte-erstellen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_inhalte-erstellen_3', c."id", 'Wie versende ich einen Newsletter?', 'Verfasse im Dashboard einen Newsletter und sende ihn an alle oder an ausgewählte Mitglieder. So erreichst du deine Community direkt in ihrem Postfach — ohne fremden Algorithmus dazwischen.', 3, true, now() FROM "HelpCategory" c WHERE c."slug"='inhalte-erstellen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_inhalte-erstellen_4', c."id", 'Was ist die Mediathek?', 'Die Mediathek ist der zentrale Ort für deine Videos, Audios und Dateien. Von dort aus bindest du sie in Beiträge, Kurse oder Events ein.', 4, true, now() FROM "HelpCategory" c WHERE c."slug"='inhalte-erstellen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_inhalte-erstellen_5', c."id", 'Kann ich Beiträge im Voraus planen?', 'Ja. Du kannst Inhalte für einen späteren Zeitpunkt planen, sodass sie automatisch erscheinen — praktisch, um regelmäßig aktiv zu bleiben.', 5, true, now() FROM "HelpCategory" c WHERE c."slug"='inhalte-erstellen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_teilnehmen_0', c."id", 'Wie trete ich einer Community bei?', 'Öffne die Community und wähle „Beitreten". Bei kostenlosen Communities bist du sofort dabei. Bei bezahlten wählst du zuerst eine Mitgliedschaft aus.', 0, true, now() FROM "HelpCategory" c WHERE c."slug"='teilnehmen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_teilnehmen_1', c."id", 'Wie schreibe ich Beiträge und Kommentare?', 'In allen Bereichen, für die du Zugang hast, kannst du Beiträge schreiben, kommentieren und reagieren — ähnlich wie in einem sozialen Netzwerk, nur ohne fremden Algorithmus.', 1, true, now() FROM "HelpCategory" c WHERE c."slug"='teilnehmen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_teilnehmen_2', c."id", 'Wo finde ich Kurse und Events?', 'Freigeschaltete Kurse findest du im Bereich „Kurse", anstehende Termine unter „Events". Was du sehen kannst, hängt von deiner Mitgliedschaft ab.', 2, true, now() FROM "HelpCategory" c WHERE c."slug"='teilnehmen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_teilnehmen_3', c."id", 'Was sind Punkte, Level und Abzeichen?', 'Für deine Aktivität sammelst du Punkte, steigst im Level auf und verdienst Abzeichen. Eine Bestenliste zeigt besonders aktive Mitglieder — das macht das Mitmachen lebendiger.', 3, true, now() FROM "HelpCategory" c WHERE c."slug"='teilnehmen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_teilnehmen_4', c."id", 'Kann ich anderen Mitgliedern schreiben?', 'Ja, sofern der Creator den Chat und Direktnachrichten aktiviert hat, kannst du dich mit anderen Mitgliedern austauschen.', 4, true, now() FROM "HelpCategory" c WHERE c."slug"='teilnehmen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_teilnehmen_5', c."id", 'Wie stelle ich meine Benachrichtigungen ein?', 'In deinen Kontoeinstellungen legst du fest, worüber du per E-Mail und in der App informiert werden möchtest.', 5, true, now() FROM "HelpCategory" c WHERE c."slug"='teilnehmen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_ki-funktionen_0', c."id", 'Was kann der KI-Assistent?', 'Der KI-Assistent hilft dir beim Schreiben von Beiträgen, Newslettern und beim Sammeln von Ideen. Er liefert einen Startpunkt, den du anpasst — die Kontrolle behältst immer du.', 0, true, now() FROM "HelpCategory" c WHERE c."slug"='ki-funktionen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_ki-funktionen_1', c."id", 'Was sind KI-Empfehlungen?', 'Aera schlägt Mitgliedern passende Inhalte vor, damit sie schneller finden, was sie interessiert. Ist keine KI aktiv, funktioniert das über eine einfache, transparente Suche nach Stichworten.', 1, true, now() FROM "HelpCategory" c WHERE c."slug"='ki-funktionen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_ki-funktionen_2', c."id", 'Was ist das KI-Guthaben?', 'KI-Funktionen verbrauchen Guthaben. Jede Community hat ein Guthaben, und bei Bedarf kannst du zusätzliche Pakete nachkaufen.', 2, true, now() FROM "HelpCategory" c WHERE c."slug"='ki-funktionen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_ki-funktionen_3', c."id", 'Was passiert, wenn das KI-Guthaben aufgebraucht ist?', 'Dann pausieren die KI-Funktionen, bis du neues Guthaben nachlädst. Alle übrigen Funktionen deiner Community laufen ganz normal weiter.', 3, true, now() FROM "HelpCategory" c WHERE c."slug"='ki-funktionen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_ki-funktionen_4', c."id", 'Werden meine Inhalte für KI-Training verwendet?', 'Nein. Deine Inhalte gehören dir. Sie werden nur genutzt, um dir die Funktionen bereitzustellen, die du selbst verwendest.', 4, true, now() FROM "HelpCategory" c WHERE c."slug"='ki-funktionen' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_konto-marke-daten_0', c."id", 'Wie ändere ich mein Profil oder Passwort?', 'In deinen Kontoeinstellungen kannst du Name, Profilbild, E-Mail-Adresse und Passwort jederzeit anpassen.', 0, true, now() FROM "HelpCategory" c WHERE c."slug"='konto-marke-daten' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_konto-marke-daten_1', c."id", 'Wie verwalte ich meine Mitglieder?', 'Im Dashboard siehst du alle Mitglieder deiner Community. Du kannst Rollen wie Moderator vergeben, neue Mitglieder einladen oder Mitglieder entfernen.', 1, true, now() FROM "HelpCategory" c WHERE c."slug"='konto-marke-daten' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_konto-marke-daten_2', c."id", 'Gehören mir meine Daten?', 'Ja. Deine Community, deine Mitgliederliste und deine Inhalte gehören dir. Du kannst deine Daten jederzeit herunterladen — du bist an nichts gebunden.', 2, true, now() FROM "HelpCategory" c WHERE c."slug"='konto-marke-daten' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_konto-marke-daten_3', c."id", 'Wie lade ich meine Daten herunter?', 'In den Einstellungen findest du den Datenexport. Damit erhältst du deine Inhalte in einem gängigen Format zum Herunterladen.', 3, true, now() FROM "HelpCategory" c WHERE c."slug"='konto-marke-daten' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_konto-marke-daten_4', c."id", 'Wie sicher sind meine Daten?', 'Jede Community ist sauber von allen anderen getrennt und geschützt, sodass niemand sonst Zugriff hat. Deine Zahlungsdaten liegen ausschließlich beim Zahlungsdienstleister, nicht bei Aera.', 4, true, now() FROM "HelpCategory" c WHERE c."slug"='konto-marke-daten' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_konto-marke-daten_5', c."id", 'Wie lösche ich meine Community oder mein Konto?', 'Das geht in den Einstellungen. Beim Löschen werden die zugehörigen Inhalte entfernt — lade dir vorher bei Bedarf deine Daten herunter.', 5, true, now() FROM "HelpCategory" c WHERE c."slug"='konto-marke-daten' ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HelpArticle" ("id","categoryId","question","answer","sortOrder","isPublished","updatedAt") SELECT 'ha_konto-marke-daten_6', c."id", 'Wie erreiche ich den Support?', 'Nutze den Kontakt-Button am Ende des Hilfe-Centers. Beschreibe dein Anliegen möglichst genau, dann können wir dir schnell weiterhelfen.', 6, true, now() FROM "HelpCategory" c WHERE c."slug"='konto-marke-daten' ON CONFLICT ("id") DO NOTHING;
