-- Reference RLS policy. Prisma migrations are the only source of truth;
-- scripts/apply-rls.ts verifies the installed role, grants and policies.
-- Every tenant-scoped table is isolated by the session GUC `aera.tenant_id`.
--
-- Enforcement model:
--   * Application-level scoping (every query filters tenantId) is the primary,
--     always-on guarantee.
--   * Global system paths use the privileged connection. Tenant-scoped Prisma
--     operations switch to the non-owner `aera_app` role and execute:
--         SET LOCAL ROLE aera_app;
--         SET LOCAL aera.tenant_id = '<tenant-id>';
--     inside the same transaction, enforcing isolation even when the physical
--     connection belongs to the table owner.
--
-- Example policy (created for each tenant table):
--   ALTER TABLE "Post" ENABLE ROW LEVEL SECURITY;
--   CREATE POLICY tenant_isolation ON "Post"
--     USING ("tenantId" = current_setting('aera.tenant_id', true))
--     WITH CHECK ("tenantId" = current_setting('aera.tenant_id', true));
--
-- New tenant tables must enable RLS, add this policy and grant their required
-- operations to aera_app in the same migration. There are intentionally no
-- blanket default table grants.

-- ---------------------------------------------------------------------------
-- Aeli (aeli.so) — zweite Rolle, anderes Kriterium
-- ---------------------------------------------------------------------------
-- Die Aeli-Tabellen (AeliProfile/AeliBlock/AeliClick/AeliLead) sind nicht
-- tenant-scoped. Sie kennen einen Besitzer und eine Oeffentlichkeit, also
-- laufen sie unter der eigenen Rolle `aeli_app` mit dem GUC `aeli.user_id`:
--
--   SET LOCAL ROLE aeli_app;
--   SELECT set_config('aeli.user_id', '<user-id>', TRUE);   -- nur im Studio
--
-- Ohne gesetzten GUC bleibt sichtbar, was `status = 'PUBLISHED'` traegt — das
-- ist der oeffentliche Lesepfad der Bio-Seite. `aeli_app` bekommt bewusst
-- keinerlei Zugriff auf `User`; die Aeli-Tabellen tragen Anzeigename und Avatar
-- selbst, und Login/Registrierung laufen ueber die privilegierte Verbindung.
--
-- Auf Aera-Inhalte hat `aeli_app` einen zweiten, eng geschnittenen Lesepfad:
-- `Space`, `Event`, `MembershipTier`, `Product` und `Course`, jeweils nur die
-- Zeilen, die ein abgemeldeter Besucher auf der Community-Seite ohnehin saehe
-- (oeffentlicher, nicht archivierter Raum ohne Bezahlschranke; veroeffentlicht;
-- Tenant aktiv). Die Spalten mit Zugriffscharakter — `meetingUrl`,
-- `downloadUrl`, `streamUrl`, Stripe-/Apple-Kennungen, Entitlement-Schluessel —
-- sind gar nicht erst gewaehrt.
--
-- Quelle: prisma/migrations/20260807120000_aeli_link_in_bio/migration.sql
--         prisma/migrations/20260808120000_aeli_aera_blocks/migration.sql
-- Pruefung: aeli.so/scripts/check-rls.ts (nicht scripts/apply-rls.ts — der
-- prueft ausschliesslich die Aera-Seite und meldete jeden Aeli-Grant an
-- `aera_app` zu Recht als Drift).
