-- New space types for Priorities 2-4: LIVE, REQUESTS, BOOKING, STORIES, TIPS, CALENDAR
ALTER TYPE "SpaceType" ADD VALUE IF NOT EXISTS 'LIVE';
ALTER TYPE "SpaceType" ADD VALUE IF NOT EXISTS 'REQUESTS';
ALTER TYPE "SpaceType" ADD VALUE IF NOT EXISTS 'BOOKING';
ALTER TYPE "SpaceType" ADD VALUE IF NOT EXISTS 'STORIES';
ALTER TYPE "SpaceType" ADD VALUE IF NOT EXISTS 'TIPS';
ALTER TYPE "SpaceType" ADD VALUE IF NOT EXISTS 'CALENDAR';
